using System.Collections;
using System.Linq;
using System.Reflection;
using System.Resources;
using KeeDroidSign.Properties;
using Xunit;

namespace KeeDroidSign.Tests.UI
{
    /// <summary>Strings.cs is generated by build/Update-Strings.ps1; it must match Strings.resx.</summary>
    public class StringsTests
    {
        [Fact]
        public void EveryResourceHasAnAccessorAndViceVersa()
        {
            var resources = Strings.ResourceManager
                .GetResourceSet(System.Globalization.CultureInfo.InvariantCulture, true, true)
                .Cast<DictionaryEntry>()
                .Select(e => (string)e.Key)
                .OrderBy(k => k)
                .ToArray();
            var accessors = typeof(Strings)
                .GetProperties(BindingFlags.Static | BindingFlags.NonPublic)
                .Where(p => p.PropertyType == typeof(string))
                .Select(p => p.Name)
                .OrderBy(k => k)
                .ToArray();

            Assert.NotEmpty(resources);
            Assert.Equal(resources, accessors);
        }

        [Fact]
        public void AccessorsReturnTheResourceText()
        {
            Assert.Equal("DroidSign", Strings.MenuRoot);
            Assert.Equal("Export to GitHub", Strings.ButtonExport);
        }
    }
}
