<Project>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Company>KeeDroidSign</Company>
    <Product>KeeDroidSign</Product>
    <Version>1.0.1</Version>
    <Copyright>Copyright (C) 2026 Oleksandr Kolodkin. Licensed under GPL-2.0-or-later.</Copyright>
    <PackageLicenseExpression>GPL-2.0-or-later</PackageLicenseExpression>
  </PropertyGroup>
</Project>
