using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// Kept in source (not generated by MSBuild) because KeePass compiles the PLGX from these files.
// KeePass only loads plugin assemblies whose AssemblyProduct is "KeePass Plugin".
[assembly: AssemblyTitle("KeeDroidSign")]
[assembly: AssemblyDescription("Android app signing keys in KeePass: JKS generation, GitHub Actions secrets, Developer Console fingerprints.")]
[assembly: AssemblyCompany("Oleksandr Kolodkin")]
[assembly: AssemblyProduct("KeePass Plugin")]
[assembly: AssemblyCopyright("Copyright (C) 2026 Oleksandr Kolodkin. Licensed under GPL-2.0-or-later.")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.1.1.0")]
[assembly: AssemblyFileVersion("1.1.1.0")]
[assembly: InternalsVisibleTo("KeeDroidSign.Tests")]
