// <auto-generated>
//   Generated by build/Update-Strings.ps1 from Strings.resx. Do not edit by hand.
// </auto-generated>
using System.Globalization;
using System.Resources;

namespace KeeDroidSign.Properties
{
    /// <summary>User-visible strings (C# 5, so KeePass can compile it as part of the PLGX).</summary>
    internal static class Strings
    {
        private static ResourceManager s_resourceManager;

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (s_resourceManager == null)
                    s_resourceManager = new ResourceManager("KeeDroidSign.Properties.Strings", typeof(Strings).Assembly);
                return s_resourceManager;
            }
        }

        internal static CultureInfo Culture { get; set; }

        internal static string AddKeyInfo
        {
            get { return ResourceManager.GetString("AddKeyInfo", Culture); }
        }

        internal static string AddKeyTitle
        {
            get { return ResourceManager.GetString("AddKeyTitle", Culture); }
        }

        internal static string AppExistsAskAddKey
        {
            get { return ResourceManager.GetString("AppExistsAskAddKey", Culture); }
        }

        internal static string ButtonCancel
        {
            get { return ResourceManager.GetString("ButtonCancel", Culture); }
        }

        internal static string ButtonClear
        {
            get { return ResourceManager.GetString("ButtonClear", Culture); }
        }

        internal static string ButtonCopy
        {
            get { return ResourceManager.GetString("ButtonCopy", Culture); }
        }

        internal static string ButtonCreate
        {
            get { return ResourceManager.GetString("ButtonCreate", Culture); }
        }

        internal static string ButtonCreateGroup
        {
            get { return ResourceManager.GetString("ButtonCreateGroup", Culture); }
        }

        internal static string ButtonExport
        {
            get { return ResourceManager.GetString("ButtonExport", Culture); }
        }

        internal static string ButtonOk
        {
            get { return ResourceManager.GetString("ButtonOk", Culture); }
        }

        internal static string ButtonSelect
        {
            get { return ResourceManager.GetString("ButtonSelect", Culture); }
        }

        internal static string ColumnGroup
        {
            get { return ResourceManager.GetString("ColumnGroup", Culture); }
        }

        internal static string ColumnTitle
        {
            get { return ResourceManager.GetString("ColumnTitle", Culture); }
        }

        internal static string ConfirmExport
        {
            get { return ResourceManager.GetString("ConfirmExport", Culture); }
        }

        internal static string ConfirmExportCreate
        {
            get { return ResourceManager.GetString("ConfirmExportCreate", Culture); }
        }

        internal static string ConfirmExportOverwrite
        {
            get { return ResourceManager.GetString("ConfirmExportOverwrite", Culture); }
        }

        internal static string ErrorNoDatabase
        {
            get { return ResourceManager.GetString("ErrorNoDatabase", Culture); }
        }

        internal static string ErrorOpenBrowser
        {
            get { return ResourceManager.GetString("ErrorOpenBrowser", Culture); }
        }

        internal static string ErrorReadKey
        {
            get { return ResourceManager.GetString("ErrorReadKey", Culture); }
        }

        internal static string ErrorUnexpected
        {
            get { return ResourceManager.GetString("ErrorUnexpected", Culture); }
        }

        internal static string ExportCancelledByUser
        {
            get { return ResourceManager.GetString("ExportCancelledByUser", Culture); }
        }

        internal static string ExportDisabledProblems
        {
            get { return ResourceManager.GetString("ExportDisabledProblems", Culture); }
        }

        internal static string ExportDisabledToken
        {
            get { return ResourceManager.GetString("ExportDisabledToken", Culture); }
        }

        internal static string ExportDone
        {
            get { return ResourceManager.GetString("ExportDone", Culture); }
        }

        internal static string FingerprintHint
        {
            get { return ResourceManager.GetString("FingerprintHint", Culture); }
        }

        internal static string GroupCreated
        {
            get { return ResourceManager.GetString("GroupCreated", Culture); }
        }

        internal static string HintPackageId
        {
            get { return ResourceManager.GetString("HintPackageId", Culture); }
        }

        internal static string HintRepository
        {
            get { return ResourceManager.GetString("HintRepository", Culture); }
        }

        internal static string KeyCreated
        {
            get { return ResourceManager.GetString("KeyCreated", Culture); }
        }

        internal static string LabelApp
        {
            get { return ResourceManager.GetString("LabelApp", Culture); }
        }

        internal static string LabelCommonName
        {
            get { return ResourceManager.GetString("LabelCommonName", Culture); }
        }

        internal static string LabelCountry
        {
            get { return ResourceManager.GetString("LabelCountry", Culture); }
        }

        internal static string LabelDisplayName
        {
            get { return ResourceManager.GetString("LabelDisplayName", Culture); }
        }

        internal static string LabelKeyNumber
        {
            get { return ResourceManager.GetString("LabelKeyNumber", Culture); }
        }

        internal static string LabelKeySize
        {
            get { return ResourceManager.GetString("LabelKeySize", Culture); }
        }

        internal static string LabelLocality
        {
            get { return ResourceManager.GetString("LabelLocality", Culture); }
        }

        internal static string LabelNewKeyNumber
        {
            get { return ResourceManager.GetString("LabelNewKeyNumber", Culture); }
        }

        internal static string LabelOrganization
        {
            get { return ResourceManager.GetString("LabelOrganization", Culture); }
        }

        internal static string LabelOrgUnit
        {
            get { return ResourceManager.GetString("LabelOrgUnit", Culture); }
        }

        internal static string LabelOwner
        {
            get { return ResourceManager.GetString("LabelOwner", Culture); }
        }

        internal static string LabelPackageId
        {
            get { return ResourceManager.GetString("LabelPackageId", Culture); }
        }

        internal static string LabelRepository
        {
            get { return ResourceManager.GetString("LabelRepository", Culture); }
        }

        internal static string LabelRepositoryShort
        {
            get { return ResourceManager.GetString("LabelRepositoryShort", Culture); }
        }

        internal static string LabelSha256
        {
            get { return ResourceManager.GetString("LabelSha256", Culture); }
        }

        internal static string LabelState
        {
            get { return ResourceManager.GetString("LabelState", Culture); }
        }

        internal static string LabelValid
        {
            get { return ResourceManager.GetString("LabelValid", Culture); }
        }

        internal static string LabelValidity
        {
            get { return ResourceManager.GetString("LabelValidity", Culture); }
        }

        internal static string MenuAddKey
        {
            get { return ResourceManager.GetString("MenuAddKey", Culture); }
        }

        internal static string MenuNewKey
        {
            get { return ResourceManager.GetString("MenuNewKey", Culture); }
        }

        internal static string MenuRoot
        {
            get { return ResourceManager.GetString("MenuRoot", Culture); }
        }

        internal static string NewKeyTitle
        {
            get { return ResourceManager.GetString("NewKeyTitle", Culture); }
        }

        internal static string NoAppsYet
        {
            get { return ResourceManager.GetString("NoAppsYet", Culture); }
        }

        internal static string NotImplemented
        {
            get { return ResourceManager.GetString("NotImplemented", Culture); }
        }

        internal static string OptionsDefaultCommonNameHint
        {
            get { return ResourceManager.GetString("OptionsDefaultCommonNameHint", Culture); }
        }

        internal static string OptionsDefaultsHeader
        {
            get { return ResourceManager.GetString("OptionsDefaultsHeader", Culture); }
        }

        internal static string OptionsGitHubOwner
        {
            get { return ResourceManager.GetString("OptionsGitHubOwner", Culture); }
        }

        internal static string OptionsNoDatabase
        {
            get { return ResourceManager.GetString("OptionsNoDatabase", Culture); }
        }

        internal static string OptionsNotSaved
        {
            get { return ResourceManager.GetString("OptionsNotSaved", Culture); }
        }

        internal static string OptionsPasswordLength
        {
            get { return ResourceManager.GetString("OptionsPasswordLength", Culture); }
        }

        internal static string OptionsRootGroup
        {
            get { return ResourceManager.GetString("OptionsRootGroup", Culture); }
        }

        internal static string OptionsSaveAfterKeyChange
        {
            get { return ResourceManager.GetString("OptionsSaveAfterKeyChange", Culture); }
        }

        internal static string OptionsSecretKeyAlias
        {
            get { return ResourceManager.GetString("OptionsSecretKeyAlias", Culture); }
        }

        internal static string OptionsSecretKeyPassword
        {
            get { return ResourceManager.GetString("OptionsSecretKeyPassword", Culture); }
        }

        internal static string OptionsSecretKeystore
        {
            get { return ResourceManager.GetString("OptionsSecretKeystore", Culture); }
        }

        internal static string OptionsSecretsHeader
        {
            get { return ResourceManager.GetString("OptionsSecretsHeader", Culture); }
        }

        internal static string OptionsSecretStorePassword
        {
            get { return ResourceManager.GetString("OptionsSecretStorePassword", Culture); }
        }

        internal static string OptionsTokenEntry
        {
            get { return ResourceManager.GetString("OptionsTokenEntry", Culture); }
        }

        internal static string OptionsTokenInfo
        {
            get { return ResourceManager.GetString("OptionsTokenInfo", Culture); }
        }

        internal static string OptionsTokenNotFound
        {
            get { return ResourceManager.GetString("OptionsTokenNotFound", Culture); }
        }

        internal static string OptionsTokenNotSelected
        {
            get { return ResourceManager.GetString("OptionsTokenNotSelected", Culture); }
        }

        internal static string PasswordsInfo
        {
            get { return ResourceManager.GetString("PasswordsInfo", Culture); }
        }

        internal static string PickerFilter
        {
            get { return ResourceManager.GetString("PickerFilter", Culture); }
        }

        internal static string PickerTitle
        {
            get { return ResourceManager.GetString("PickerTitle", Culture); }
        }

        internal static string ProblemInvalidRepository
        {
            get { return ResourceManager.GetString("ProblemInvalidRepository", Culture); }
        }

        internal static string ProblemMissingKeyNumber
        {
            get { return ResourceManager.GetString("ProblemMissingKeyNumber", Culture); }
        }

        internal static string ProblemMissingKeystoreEntry
        {
            get { return ResourceManager.GetString("ProblemMissingKeystoreEntry", Culture); }
        }

        internal static string ProblemMissingKeystoreFile
        {
            get { return ResourceManager.GetString("ProblemMissingKeystoreFile", Culture); }
        }

        internal static string ProblemMissingRepository
        {
            get { return ResourceManager.GetString("ProblemMissingRepository", Culture); }
        }

        internal static string StatusCancelled
        {
            get { return ResourceManager.GetString("StatusCancelled", Culture); }
        }

        internal static string StatusExporting
        {
            get { return ResourceManager.GetString("StatusExporting", Culture); }
        }

        internal static string StatusGenerating
        {
            get { return ResourceManager.GetString("StatusGenerating", Culture); }
        }

        internal static string TabTitle
        {
            get { return ResourceManager.GetString("TabTitle", Culture); }
        }
    }
}
