// <auto-generated>
//   Generated by build/Update-Strings.ps1 from Strings.resx. Do not edit by hand.
// </auto-generated>
using System.Globalization;
using System.Resources;

namespace KeeDroidSign.Properties
{
    /// <summary>User-visible strings (C# 5, so KeePass can compile it as part of the PLGX).</summary>
    internal static class Strings
    {
        private static ResourceManager s_resourceManager;

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (s_resourceManager == null)
                    s_resourceManager = new ResourceManager("KeeDroidSign.Properties.Strings", typeof(Strings).Assembly);
                return s_resourceManager;
            }
        }

        internal static CultureInfo Culture { get; set; }

        internal static string ActionBranchGroup
        {
            get { return ResourceManager.GetString("ActionBranchGroup", Culture); }
        }

        internal static string ActionBranchProtect
        {
            get { return ResourceManager.GetString("ActionBranchProtect", Culture); }
        }

        internal static string ActionCleanup
        {
            get { return ResourceManager.GetString("ActionCleanup", Culture); }
        }

        internal static string ActionCreateEnvironment
        {
            get { return ResourceManager.GetString("ActionCreateEnvironment", Culture); }
        }

        internal static string ActionExport
        {
            get { return ResourceManager.GetString("ActionExport", Culture); }
        }

        internal static string ActionExportBlocked
        {
            get { return ResourceManager.GetString("ActionExportBlocked", Culture); }
        }

        internal static string ActionLeave
        {
            get { return ResourceManager.GetString("ActionLeave", Culture); }
        }

        internal static string ActionNeedsAdministration
        {
            get { return ResourceManager.GetString("ActionNeedsAdministration", Culture); }
        }

        internal static string ActionProtectNote
        {
            get { return ResourceManager.GetString("ActionProtectNote", Culture); }
        }

        internal static string ActionRestrictEnvironment
        {
            get { return ResourceManager.GetString("ActionRestrictEnvironment", Culture); }
        }

        internal static string ActionTagsGroup
        {
            get { return ResourceManager.GetString("ActionTagsGroup", Culture); }
        }

        internal static string ActionTagsRemove
        {
            get { return ResourceManager.GetString("ActionTagsRemove", Culture); }
        }

        internal static string ActionTagsRestrict
        {
            get { return ResourceManager.GetString("ActionTagsRestrict", Culture); }
        }

        internal static string AddKeyInfo
        {
            get { return ResourceManager.GetString("AddKeyInfo", Culture); }
        }

        internal static string AddKeyOwnerHint
        {
            get { return ResourceManager.GetString("AddKeyOwnerHint", Culture); }
        }

        internal static string AddKeyTitle
        {
            get { return ResourceManager.GetString("AddKeyTitle", Culture); }
        }

        internal static string AppExistsAskAddKey
        {
            get { return ResourceManager.GetString("AppExistsAskAddKey", Culture); }
        }

        internal static string ButtonBack
        {
            get { return ResourceManager.GetString("ButtonBack", Culture); }
        }

        internal static string ButtonCancel
        {
            get { return ResourceManager.GetString("ButtonCancel", Culture); }
        }

        internal static string ButtonClear
        {
            get { return ResourceManager.GetString("ButtonClear", Culture); }
        }

        internal static string ButtonClose
        {
            get { return ResourceManager.GetString("ButtonClose", Culture); }
        }

        internal static string ButtonCopy
        {
            get { return ResourceManager.GetString("ButtonCopy", Culture); }
        }

        internal static string ButtonCreate
        {
            get { return ResourceManager.GetString("ButtonCreate", Culture); }
        }

        internal static string ButtonCreateGroup
        {
            get { return ResourceManager.GetString("ButtonCreateGroup", Culture); }
        }

        internal static string ButtonExport
        {
            get { return ResourceManager.GetString("ButtonExport", Culture); }
        }

        internal static string ButtonFinish
        {
            get { return ResourceManager.GetString("ButtonFinish", Culture); }
        }

        internal static string ButtonNext
        {
            get { return ResourceManager.GetString("ButtonNext", Culture); }
        }

        internal static string ButtonOk
        {
            get { return ResourceManager.GetString("ButtonOk", Culture); }
        }

        internal static string ButtonRun
        {
            get { return ResourceManager.GetString("ButtonRun", Culture); }
        }

        internal static string ButtonSelect
        {
            get { return ResourceManager.GetString("ButtonSelect", Culture); }
        }

        internal static string CheckExportNow
        {
            get { return ResourceManager.GetString("CheckExportNow", Culture); }
        }

        internal static string ColumnGroup
        {
            get { return ResourceManager.GetString("ColumnGroup", Culture); }
        }

        internal static string ColumnTitle
        {
            get { return ResourceManager.GetString("ColumnTitle", Culture); }
        }

        internal static string CreateGroupInfo
        {
            get { return ResourceManager.GetString("CreateGroupInfo", Culture); }
        }

        internal static string CreateGroupTitle
        {
            get { return ResourceManager.GetString("CreateGroupTitle", Culture); }
        }

        internal static string DefaultTargetEnvironment
        {
            get { return ResourceManager.GetString("DefaultTargetEnvironment", Culture); }
        }

        internal static string DefaultTargetRepository
        {
            get { return ResourceManager.GetString("DefaultTargetRepository", Culture); }
        }

        internal static string EnvironmentManualSteps
        {
            get { return ResourceManager.GetString("EnvironmentManualSteps", Culture); }
        }

        internal static string ErrorGroupExists
        {
            get { return ResourceManager.GetString("ErrorGroupExists", Culture); }
        }

        internal static string ErrorGroupName
        {
            get { return ResourceManager.GetString("ErrorGroupName", Culture); }
        }

        internal static string ErrorNoDatabase
        {
            get { return ResourceManager.GetString("ErrorNoDatabase", Culture); }
        }

        internal static string ErrorOpenBrowser
        {
            get { return ResourceManager.GetString("ErrorOpenBrowser", Culture); }
        }

        internal static string ErrorReadKey
        {
            get { return ResourceManager.GetString("ErrorReadKey", Culture); }
        }

        internal static string ErrorUnexpected
        {
            get { return ResourceManager.GetString("ErrorUnexpected", Culture); }
        }

        internal static string ExportDisabledProblems
        {
            get { return ResourceManager.GetString("ExportDisabledProblems", Culture); }
        }

        internal static string ExportDisabledToken
        {
            get { return ResourceManager.GetString("ExportDisabledToken", Culture); }
        }

        internal static string FindingBranchProtected
        {
            get { return ResourceManager.GetString("FindingBranchProtected", Culture); }
        }

        internal static string FindingBranchUnknown
        {
            get { return ResourceManager.GetString("FindingBranchUnknown", Culture); }
        }

        internal static string FindingBranchUnprotected
        {
            get { return ResourceManager.GetString("FindingBranchUnprotected", Culture); }
        }

        internal static string FindingCopies
        {
            get { return ResourceManager.GetString("FindingCopies", Culture); }
        }

        internal static string FindingEnvironmentAllBranches
        {
            get { return ResourceManager.GetString("FindingEnvironmentAllBranches", Culture); }
        }

        internal static string FindingEnvironmentMissing
        {
            get { return ResourceManager.GetString("FindingEnvironmentMissing", Culture); }
        }

        internal static string FindingEnvironmentNoPatterns
        {
            get { return ResourceManager.GetString("FindingEnvironmentNoPatterns", Culture); }
        }

        internal static string FindingEnvironmentPatterns
        {
            get { return ResourceManager.GetString("FindingEnvironmentPatterns", Culture); }
        }

        internal static string FindingEnvironmentProtectedBranches
        {
            get { return ResourceManager.GetString("FindingEnvironmentProtectedBranches", Culture); }
        }

        internal static string FindingEnvironmentUnknown
        {
            get { return ResourceManager.GetString("FindingEnvironmentUnknown", Culture); }
        }

        internal static string FindingRepositorySecrets
        {
            get { return ResourceManager.GetString("FindingRepositorySecrets", Culture); }
        }

        internal static string FindingSecretsNew
        {
            get { return ResourceManager.GetString("FindingSecretsNew", Culture); }
        }

        internal static string FindingSecretsOverwrite
        {
            get { return ResourceManager.GetString("FindingSecretsOverwrite", Culture); }
        }

        internal static string FindingTagsRestricted
        {
            get { return ResourceManager.GetString("FindingTagsRestricted", Culture); }
        }

        internal static string FindingTagsUnknown
        {
            get { return ResourceManager.GetString("FindingTagsUnknown", Culture); }
        }

        internal static string FindingTagsUnrestricted
        {
            get { return ResourceManager.GetString("FindingTagsUnrestricted", Culture); }
        }

        internal static string FingerprintHint
        {
            get { return ResourceManager.GetString("FingerprintHint", Culture); }
        }

        internal static string GitHubEnvironmentHint
        {
            get { return ResourceManager.GetString("GitHubEnvironmentHint", Culture); }
        }

        internal static string HintPackageId
        {
            get { return ResourceManager.GetString("HintPackageId", Culture); }
        }

        internal static string HintRepository
        {
            get { return ResourceManager.GetString("HintRepository", Culture); }
        }

        internal static string KeyCreated
        {
            get { return ResourceManager.GetString("KeyCreated", Culture); }
        }

        internal static string LabelApp
        {
            get { return ResourceManager.GetString("LabelApp", Culture); }
        }

        internal static string LabelCommonName
        {
            get { return ResourceManager.GetString("LabelCommonName", Culture); }
        }

        internal static string LabelCountry
        {
            get { return ResourceManager.GetString("LabelCountry", Culture); }
        }

        internal static string LabelDisplayName
        {
            get { return ResourceManager.GetString("LabelDisplayName", Culture); }
        }

        internal static string LabelGitHubEnvironment
        {
            get { return ResourceManager.GetString("LabelGitHubEnvironment", Culture); }
        }

        internal static string LabelGroupName
        {
            get { return ResourceManager.GetString("LabelGroupName", Culture); }
        }

        internal static string LabelKeyNumber
        {
            get { return ResourceManager.GetString("LabelKeyNumber", Culture); }
        }

        internal static string LabelKeySize
        {
            get { return ResourceManager.GetString("LabelKeySize", Culture); }
        }

        internal static string LabelLocality
        {
            get { return ResourceManager.GetString("LabelLocality", Culture); }
        }

        internal static string LabelNewKeyNumber
        {
            get { return ResourceManager.GetString("LabelNewKeyNumber", Culture); }
        }

        internal static string LabelOrganization
        {
            get { return ResourceManager.GetString("LabelOrganization", Culture); }
        }

        internal static string LabelOrgUnit
        {
            get { return ResourceManager.GetString("LabelOrgUnit", Culture); }
        }

        internal static string LabelOwner
        {
            get { return ResourceManager.GetString("LabelOwner", Culture); }
        }

        internal static string LabelPackageId
        {
            get { return ResourceManager.GetString("LabelPackageId", Culture); }
        }

        internal static string LabelRepository
        {
            get { return ResourceManager.GetString("LabelRepository", Culture); }
        }

        internal static string LabelRepositoryShort
        {
            get { return ResourceManager.GetString("LabelRepositoryShort", Culture); }
        }

        internal static string LabelSha256
        {
            get { return ResourceManager.GetString("LabelSha256", Culture); }
        }

        internal static string LabelState
        {
            get { return ResourceManager.GetString("LabelState", Culture); }
        }

        internal static string LabelValid
        {
            get { return ResourceManager.GetString("LabelValid", Culture); }
        }

        internal static string LabelValidity
        {
            get { return ResourceManager.GetString("LabelValidity", Culture); }
        }

        internal static string MenuAddKey
        {
            get { return ResourceManager.GetString("MenuAddKey", Culture); }
        }

        internal static string MenuNewKey
        {
            get { return ResourceManager.GetString("MenuNewKey", Culture); }
        }

        internal static string MenuRoot
        {
            get { return ResourceManager.GetString("MenuRoot", Culture); }
        }

        internal static string NewKeyDoneInfo
        {
            get { return ResourceManager.GetString("NewKeyDoneInfo", Culture); }
        }

        internal static string NewKeyDoneNoToken
        {
            get { return ResourceManager.GetString("NewKeyDoneNoToken", Culture); }
        }

        internal static string NewKeyIntroApp
        {
            get { return ResourceManager.GetString("NewKeyIntroApp", Culture); }
        }

        internal static string NewKeyIntroOwner
        {
            get { return ResourceManager.GetString("NewKeyIntroOwner", Culture); }
        }

        internal static string NewKeyStepDone
        {
            get { return ResourceManager.GetString("NewKeyStepDone", Culture); }
        }

        internal static string NewKeySubtitle
        {
            get { return ResourceManager.GetString("NewKeySubtitle", Culture); }
        }

        internal static string NewKeyTitle
        {
            get { return ResourceManager.GetString("NewKeyTitle", Culture); }
        }

        internal static string NoAppsYet
        {
            get { return ResourceManager.GetString("NoAppsYet", Culture); }
        }

        internal static string NotImplemented
        {
            get { return ResourceManager.GetString("NotImplemented", Culture); }
        }

        internal static string OptionsDefaultCommonNameHint
        {
            get { return ResourceManager.GetString("OptionsDefaultCommonNameHint", Culture); }
        }

        internal static string OptionsGitHubOwner
        {
            get { return ResourceManager.GetString("OptionsGitHubOwner", Culture); }
        }

        internal static string OptionsGitHubOwnerHint
        {
            get { return ResourceManager.GetString("OptionsGitHubOwnerHint", Culture); }
        }

        internal static string OptionsNewKeysInfo
        {
            get { return ResourceManager.GetString("OptionsNewKeysInfo", Culture); }
        }

        internal static string OptionsNoDatabase
        {
            get { return ResourceManager.GetString("OptionsNoDatabase", Culture); }
        }

        internal static string OptionsNotSaved
        {
            get { return ResourceManager.GetString("OptionsNotSaved", Culture); }
        }

        internal static string OptionsPasswordLength
        {
            get { return ResourceManager.GetString("OptionsPasswordLength", Culture); }
        }

        internal static string OptionsRootGroup
        {
            get { return ResourceManager.GetString("OptionsRootGroup", Culture); }
        }

        internal static string OptionsSaveAfterKeyChange
        {
            get { return ResourceManager.GetString("OptionsSaveAfterKeyChange", Culture); }
        }

        internal static string OptionsSecretKeyAlias
        {
            get { return ResourceManager.GetString("OptionsSecretKeyAlias", Culture); }
        }

        internal static string OptionsSecretKeyPassword
        {
            get { return ResourceManager.GetString("OptionsSecretKeyPassword", Culture); }
        }

        internal static string OptionsSecretKeystore
        {
            get { return ResourceManager.GetString("OptionsSecretKeystore", Culture); }
        }

        internal static string OptionsSecretsInfo
        {
            get { return ResourceManager.GetString("OptionsSecretsInfo", Culture); }
        }

        internal static string OptionsSecretStorePassword
        {
            get { return ResourceManager.GetString("OptionsSecretStorePassword", Culture); }
        }

        internal static string OptionsSectionDatabase
        {
            get { return ResourceManager.GetString("OptionsSectionDatabase", Culture); }
        }

        internal static string OptionsSectionGitHub
        {
            get { return ResourceManager.GetString("OptionsSectionGitHub", Culture); }
        }

        internal static string OptionsTabGeneral
        {
            get { return ResourceManager.GetString("OptionsTabGeneral", Culture); }
        }

        internal static string OptionsTabNewKeys
        {
            get { return ResourceManager.GetString("OptionsTabNewKeys", Culture); }
        }

        internal static string OptionsTabSecrets
        {
            get { return ResourceManager.GetString("OptionsTabSecrets", Culture); }
        }

        internal static string OptionsTokenEntry
        {
            get { return ResourceManager.GetString("OptionsTokenEntry", Culture); }
        }

        internal static string OptionsTokenInfo
        {
            get { return ResourceManager.GetString("OptionsTokenInfo", Culture); }
        }

        internal static string OptionsTokenNotFound
        {
            get { return ResourceManager.GetString("OptionsTokenNotFound", Culture); }
        }

        internal static string OptionsTokenNotSelected
        {
            get { return ResourceManager.GetString("OptionsTokenNotSelected", Culture); }
        }

        internal static string PasswordsInfo
        {
            get { return ResourceManager.GetString("PasswordsInfo", Culture); }
        }

        internal static string PickerFilter
        {
            get { return ResourceManager.GetString("PickerFilter", Culture); }
        }

        internal static string PickerTitle
        {
            get { return ResourceManager.GetString("PickerTitle", Culture); }
        }

        internal static string ProblemInvalidRepository
        {
            get { return ResourceManager.GetString("ProblemInvalidRepository", Culture); }
        }

        internal static string ProblemMissingKeyNumber
        {
            get { return ResourceManager.GetString("ProblemMissingKeyNumber", Culture); }
        }

        internal static string ProblemMissingKeystoreEntry
        {
            get { return ResourceManager.GetString("ProblemMissingKeystoreEntry", Culture); }
        }

        internal static string ProblemMissingKeystoreFile
        {
            get { return ResourceManager.GetString("ProblemMissingKeystoreFile", Culture); }
        }

        internal static string ProblemMissingRepository
        {
            get { return ResourceManager.GetString("ProblemMissingRepository", Culture); }
        }

        internal static string RadioEnvironment
        {
            get { return ResourceManager.GetString("RadioEnvironment", Culture); }
        }

        internal static string RadioRepositoryLevel
        {
            get { return ResourceManager.GetString("RadioRepositoryLevel", Culture); }
        }

        internal static string RadioUseDefault
        {
            get { return ResourceManager.GetString("RadioUseDefault", Culture); }
        }

        internal static string ResultDone
        {
            get { return ResourceManager.GetString("ResultDone", Culture); }
        }

        internal static string ResultFailed
        {
            get { return ResourceManager.GetString("ResultFailed", Culture); }
        }

        internal static string ResultSkippedCleanup
        {
            get { return ResourceManager.GetString("ResultSkippedCleanup", Culture); }
        }

        internal static string ResultSkippedExport
        {
            get { return ResourceManager.GetString("ResultSkippedExport", Culture); }
        }

        internal static string SectionApp
        {
            get { return ResourceManager.GetString("SectionApp", Culture); }
        }

        internal static string SectionKey
        {
            get { return ResourceManager.GetString("SectionKey", Culture); }
        }

        internal static string SectionOwner
        {
            get { return ResourceManager.GetString("SectionOwner", Culture); }
        }

        internal static string StatusCancelled
        {
            get { return ResourceManager.GetString("StatusCancelled", Culture); }
        }

        internal static string StatusGenerating
        {
            get { return ResourceManager.GetString("StatusGenerating", Culture); }
        }

        internal static string StatusInspecting
        {
            get { return ResourceManager.GetString("StatusInspecting", Culture); }
        }

        internal static string StatusRunning
        {
            get { return ResourceManager.GetString("StatusRunning", Culture); }
        }

        internal static string TabTitle
        {
            get { return ResourceManager.GetString("TabTitle", Culture); }
        }

        internal static string TargetEnvironmentFmt
        {
            get { return ResourceManager.GetString("TargetEnvironmentFmt", Culture); }
        }

        internal static string TargetHintDefaultEnvironment
        {
            get { return ResourceManager.GetString("TargetHintDefaultEnvironment", Culture); }
        }

        internal static string TargetHintDefaultRepository
        {
            get { return ResourceManager.GetString("TargetHintDefaultRepository", Culture); }
        }

        internal static string TargetHintEnvironment
        {
            get { return ResourceManager.GetString("TargetHintEnvironment", Culture); }
        }

        internal static string TargetHintRepository
        {
            get { return ResourceManager.GetString("TargetHintRepository", Culture); }
        }

        internal static string TargetRemembered
        {
            get { return ResourceManager.GetString("TargetRemembered", Culture); }
        }

        internal static string TargetRepositoryFmt
        {
            get { return ResourceManager.GetString("TargetRepositoryFmt", Culture); }
        }

        internal static string WarningRepositoryCopiesKept
        {
            get { return ResourceManager.GetString("WarningRepositoryCopiesKept", Culture); }
        }

        internal static string WarningRepositoryCopiesUnchecked
        {
            get { return ResourceManager.GetString("WarningRepositoryCopiesUnchecked", Culture); }
        }

        internal static string WizardActions
        {
            get { return ResourceManager.GetString("WizardActions", Culture); }
        }

        internal static string WizardFindings
        {
            get { return ResourceManager.GetString("WizardFindings", Culture); }
        }

        internal static string WizardReviewHeader
        {
            get { return ResourceManager.GetString("WizardReviewHeader", Culture); }
        }

        internal static string WizardStepFmt
        {
            get { return ResourceManager.GetString("WizardStepFmt", Culture); }
        }

        internal static string WizardStepResults
        {
            get { return ResourceManager.GetString("WizardStepResults", Culture); }
        }

        internal static string WizardStepReview
        {
            get { return ResourceManager.GetString("WizardStepReview", Culture); }
        }

        internal static string WizardStepTarget
        {
            get { return ResourceManager.GetString("WizardStepTarget", Culture); }
        }

        internal static string WizardTitle
        {
            get { return ResourceManager.GetString("WizardTitle", Culture); }
        }
    }
}
